export const PATHS = {
  HOME: '/',
  PETS: '/pets',
  PETS_LANDING: '/pets/landing',
  PETS_LIST: '/pets/list',
  PRODUCTS: '/products',
  PRODUCTS_LIST: '/products/list',
  SERVICES: '/services',
  ABOUT: '/about',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PROFILE: '/profile',
  AUTH: {
    LOGIN: '/login',
    LOGIN_AFTER_LOGOUT: '/login?logout=success',
    REGISTER: '/register',
    FORGET_PASSWORD: '/forget-password',
    RESET_PASSWORD: '/reset-password',
  },
  UI_COMPONENTS: '/ui-components',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_PET_TYPES: '/admin/pet-types',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_BREEDS: '/admin/breeds',
} as const;

export const routePaths = {
  home: PATHS.HOME,
  pets: PATHS.PETS,
  petsLanding: PATHS.PETS_LANDING,
  petsList: PATHS.PETS_LIST,
  petDetail: (slug: string) => `${PATHS.PETS}/${encodeURIComponent(slug)}`,
  products: PATHS.PRODUCTS,
  productsList: PATHS.PRODUCTS_LIST,
  productDetail: (slug: string) => `${PATHS.PRODUCTS}/${encodeURIComponent(slug)}`,
  productsSearch: (query: string) => `${PATHS.PRODUCTS}?q=${encodeURIComponent(query)}`,
  services: PATHS.SERVICES,
  about: PATHS.ABOUT,
  cart: PATHS.CART,
  checkout: PATHS.CHECKOUT,
  profile: PATHS.PROFILE,
  login: PATHS.AUTH.LOGIN,
  register: PATHS.AUTH.REGISTER,
  forgetPassword: PATHS.AUTH.FORGET_PASSWORD,
  resetPassword: PATHS.AUTH.RESET_PASSWORD,
  uiComponents: PATHS.UI_COMPONENTS,
  admin: PATHS.ADMIN,
  adminUsers: PATHS.ADMIN_USERS,
  adminPetTypes: PATHS.ADMIN_PET_TYPES,
  adminCategories: PATHS.ADMIN_CATEGORIES,
  adminBreeds: PATHS.ADMIN_BREEDS,
  adminBreedsQuery: (query: URLSearchParams) => `${PATHS.ADMIN_BREEDS}?${query.toString()}`,
  adminUsersQuery: (query: URLSearchParams) => `${PATHS.ADMIN_USERS}?${query.toString()}`,
  adminUsersPage: (page: number, query = new URLSearchParams()) => {
    const searchParams = new URLSearchParams(query);
    searchParams.set('page', String(page));
    return `${PATHS.ADMIN_USERS}?${searchParams.toString()}`;
  },
  adminPage: (page: string) => `${PATHS.ADMIN}/${encodeURIComponent(page)}`,
} as const;
