export const PATHS = {
  HOME: '/',
  PETS: '/pets',
  PETS_LANDING: '/pets/landing',
  PETS_LIST: '/pets/list',
  PRODUCTS: '/products',
  PRODUCTS_LIST: '/products/list',
  SERVICES: '/services',
  ABOUT: '/about',
  CART: '/cart',
  PROFILE: '/profile',
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGET_PASSWORD: '/forget-password',
  },
  UI_COMPONENTS: '/ui-components',
} as const;

export const routePaths = {
  home: PATHS.HOME,
  pets: PATHS.PETS,
  petsLanding: PATHS.PETS_LANDING,
  petsList: PATHS.PETS_LIST,
  products: PATHS.PRODUCTS,
  productsList: PATHS.PRODUCTS_LIST,
  productDetail: (slug: string) => `${PATHS.PRODUCTS}/${encodeURIComponent(slug)}`,
  productsSearch: (query: string) => `${PATHS.PRODUCTS}?q=${encodeURIComponent(query)}`,
  services: PATHS.SERVICES,
  about: PATHS.ABOUT,
  cart: PATHS.CART,
  profile: PATHS.PROFILE,
  login: PATHS.AUTH.LOGIN,
  register: PATHS.AUTH.REGISTER,
  forgetPassword: PATHS.AUTH.FORGET_PASSWORD,
  uiComponents: PATHS.UI_COMPONENTS,
} as const;
