import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { cn } from '@/lib/utils';

import './styles/tailwind.config.css';

const iranYekan = localFont({
  src: [
    {
      path: '../../public/fonts/iran-yekan/light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/extra-bold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-iran-yekan',
  display: 'swap',
  fallback: ['Tahoma', 'Arial', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={cn('h-full antialiased font-sans', iranYekan.variable)}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
