import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { RtlLayout } from '@/components/layouts/rtl-layout';
import { cn } from '@/lib/utils';

import './styles/tailwind.config.css';

const defaultFont = localFont({
  src: [
    {
      path: '../../public/fonts/iran-yekan/light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/extra-bold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-default',
  display: 'swap',
  fallback: ['Tahoma', 'Arial', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="fa" dir="rtl" className={cn('tw:h-full tw:antialiased', defaultFont.variable)}>
      <body className="min-h-full flex flex-col">
        <RtlLayout>{children}</RtlLayout>
      </body>
    </html>
  );
}
