import 'reflect-metadata';

import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Suspense } from 'react';

import { NavigationPageBar } from '@/components/common/navigation-page-bar';
import { RtlLayout } from '@/components/layouts/rtl-layout';
import { ThemeProvider } from '@/components/layouts/theme-provider';
import { Toaster } from '@/components/ui/toast';
import { appLogo } from '@/configs/app-logo';
import { cn } from '@/lib/utils';

import { ReactQueryProvider } from './react-query-provider';
import { AuthSessionInitializer } from './_components/auth-session-initializer';
import { CartSyncInitializer } from './_components/cart-sync-initializer';

import './styles/tailwind.config.css';

const defaultFont = localFont({
  src: [
    {
      path: '../../public/fonts/iran-yekan/light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iran-yekan/extra-bold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-default',
  display: 'swap',
  fallback: ['Tahoma', 'Arial', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: appLogo.src,
      type: appLogo.type,
    },
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      suppressHydrationWarning
      className={cn('tw:h-full tw:antialiased', defaultFont.variable)}
    >
      <body
        suppressHydrationWarning
        className="tw:flex tw:min-h-full tw:flex-col tw:bg-background tw:text-foreground"
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavigationPageBar />
          <RtlLayout>
            <ReactQueryProvider>
              <AuthSessionInitializer />
              <Suspense fallback={null}>
                <CartSyncInitializer />
              </Suspense>
              <Toaster>{children}</Toaster>
            </ReactQueryProvider>
          </RtlLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
